### ISSUE TITLE
getParameters failed

### ISSUE THREAD

**Issue by frinda** [bertsir/zBarLibary#101]
小米5android版本8.0.0  魅族 16thandroid版本8.1.0这两种机型上出现
java.lang.RuntimeException: getParameters failed (empty parameters)
    at android.hardware.Camera.native_getParameters(Native Method)
    at android.hardware.Camera.getParameters(Camera.java:2110)
    at cn.bertsir.zbar.CameraScanAnalysis.onPreviewFrame(CameraScanAnalysis.java:133)
    at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1241)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:173)
    at android.app.ActivityThread.main(ActivityThread.java:6698)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by bertsir** [comment]
@frinda 有闪退么？

**Comment by frinda** [comment]
对的，就是闪退

**Comment by bertsir** [comment]
@frinda 好的 我检查一下原因，今天修复

**Comment by bertsir** [comment]
@frinda 方便给我一个你的QQ么，我手头没这两个机型，需要协助验证一下

**Comment by frinda** [comment]
我也没这两款机型，我在后台看到的bug统计

**Comment by frinda** [comment]
你到Testin上注册一账户，上面有各种各样的机型随你用，也方便调式

**Comment by bertsir** [comment]
@frinda 好的

**Comment by frinda** [comment]
这个问题解决了么

**Comment by Demonhuang** [comment]
> 这个问题解决了么

请问 你这个问题解决了么
