### ISSUE TITLE
扫描相册选择的二维码的时候会崩溃

### ISSUE THREAD

**Issue by linzh93** [bertsir/zBarLibary#15]
报错Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:1459100 flg=0x1 }} to activity {
/cn.bertsir.zbar.QRActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.，QRActivity能不能兼容下？

**Comment by bertsir** [comment]
@linzh93 感觉像是7.0的ContentProvider的问题，你是不是clone的源码提高了版本号

**Comment by linzh93** [comment]
我是直接as compile的，minSdkVersion是18 compileSdkVersion是25，用的8.0的测试机会报这个错

**Comment by bertsir** [comment]
@linzh93 targetSdkVersion多少呢

**Comment by linzh93** [comment]
@bertsir   也是25呢

**Comment by bertsir** [comment]
@linzh93 暂时降到22试一下看还有这问题么

**Comment by linzh93** [comment]
@bertsir  我把target降到22了还是有这个问题

**Comment by linzh93** [comment]
@bertsir  应该是你那边style里得做下兼容把

**Comment by bertsir** [comment]
@linzh93 具体是什么机型呢

**Comment by linzh93** [comment]
@bertsir  一加3t    android版本8.0

**Comment by GithubRyze** [comment]
不知道 楼主是否做和zxing的比较，  比如相同的分辨率下：识别的快慢？ 最长的扫描距离？等等那个更好。

**Comment by rebertBen** [comment]
android 手机8.0系统，选择相册二维码的时候，手机识别失败，楼主好好的看一下！图片是截图二维码，图片包含其他非二维码文字信息识别失败，截图后只有二维码信息，也识别失败。

**Comment by rebertBen** [comment]
09-08 15:07:12.319 23482-23482/com.chnsys.szyfy W/System.err: java.lang.RuntimeException: autoFocus failed
09-08 15:07:12.320 23482-23482/com.chnsys.szyfy W/System.err:     at android.hardware.Camera.native_autoFocus(Native Method)
        at android.hardware.Camera.autoFocus(Camera.java:1331)
        at cn.bertsir.zbar.CameraManager.autoFocus(CameraManager.java:142)
        at cn.bertsir.zbar.CameraPreview.startCameraPreview(CameraPreview.java:98)
        at cn.bertsir.zbar.CameraPreview.start(CameraPreview.java:80)
        at cn.bertsir.zbar.QRActivity.onResume(QRActivity.java:68)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1364)
        at android.app.Activity.performResume(Activity.java:7479)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4147)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
09-08 15:07:12.323 23482-23482/com.chnsys.szyfy I/PressGestureDetector: enabledInPad = false,isPcCastMode = false
09-08 15:07:12.330 1214-1303/? V/WindowManager: Checking 1 opening apps (frozen=false timeout=false)...

**Comment by bertsir** [comment]
@rebertBen 给我一个你的联系方式 方便测试

**Comment by rebertBen** [comment]
QQ 409342223

**Comment by appdev** [comment]
遇到同样问题。
```
compileSdkVersion = 28
buildToolsVersion = '28.0.3'
targetSdkVersion = 28
```

**Comment by appdev** [comment]
添加了这个库以后会提示
```
You need to use a Theme.AppCompat theme (or descendant) with this activity.
```
app崩溃

**Comment by sindicly** [comment]
SdkVersion如果是30   
不支持.setNeedCrop(true) //是否从相册选择后裁剪图片
