### ISSUE TITLE
android4.2.2报错

### ISSUE THREAD

**Issue by Superingxz** [bertsir/zBarLibary#30]
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1654): could not load library "libiconv.so" needed by "libzbar.so"; caused by load_library(linker.cpp:761): library "libiconv.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:514)
        at cn.bertsir.zbar.Qr.Symbol.<clinit>(Symbol.java:162)
        at cn.bertsir.zbar.QRActivity.onCreate(QRActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:5211)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1151)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
        at android.app.ActivityThread.access$600(ActivityThread.java:171)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5468)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by bertsir** [comment]
@Superingxz 暂时只支持4.3+
