### ISSUE TITLE
用方式二引入，但是照片扫码的id找不到

### ISSUE THREAD

**Issue by 17199913712** [bertsir/zBarLibary#39]
ProgressBar pb_loading = (ProgressBar) view.findViewById(**R.id.pb_loading**);
TextView tv_hint = (TextView) view.findViewById(**R.id.tv_hint**);

这2个Id找不到，在layout中是有该R.layout.dialog_loading的，但就是报红了，然后进去做相册扫码的时候崩溃了，不能修改class文件，只能修改xml，但没意义。

小米4，6.0.1系统

**Comment by bertsir** [comment]
@17199913712 是否能提供截图

**Comment by 17199913712** [comment]
![1](https://user-images.githubusercontent.com/39581134/50536181-a4387080-0b8c-11e9-895e-ab3c75a5e3f1.png)
![2](https://user-images.githubusercontent.com/39581134/50536182-a5699d80-0b8c-11e9-93e9-28bf9456a70e.png)

**Comment by bertsir** [comment]
@17199913712 导入的源码？

**Comment by 17199913712** [comment]
是的，标题也写了是用方式二引入的。
  //zBar
    implementation 'cn.bertsir.zbarLibary:zbarlibary:latest.release'
    implementation 'cn.bertsir.zbarLibary:zbarlibary:1.1.7'
![qq 20181229175427](https://user-images.githubusercontent.com/39581134/50536768-e795dd80-0b92-11e9-82eb-f57e13ae4905.png)

**Comment by bertsir** [comment]
@17199913712 尝试一下换个手机或者先取消引入 rebuild 然后再引入

**Comment by 17199913712** [comment]
按你说的都尝试过了，还是一样，cleanProject，Rebuild Project，Make Project，Sync Project，都没用，未运行都看都已报红状态（所以跟手机 没什么关系？），进系统相册再次选择照片进行扫描依然还是崩溃了，错误信息毅然如此（已删除整个build文件夹）/（已更换手机）。
12-29 18:17:24.681 22292-22292/com.www.tms E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.www.tms, PID: 22292
    java.lang.NoSuchFieldError: No static field pb_loading of type I in class Lcn/bertsir/zbar/R$id; or its superclasses (declaration of 'cn.bertsir.zbar.R$id' appears in /data/app/com.www.tms-1/split_lib_slice_5_apk.apk)
        at cn.bertsir.zbar.QRActivity.showProgressDialog(QRActivity.java:251)
        at cn.bertsir.zbar.QRActivity.onActivityResult(QRActivity.java:191)
        at android.app.Activity.dispatchActivityResult(Activity.java:6282)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4042)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4089)
        at android.app.ActivityThread.access$1400(ActivityThread.java:186)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:200)
        at android.app.ActivityThread.main(ActivityThread.java:5877)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
