### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Superingxz** [bertsir/zBarLibary#42]
01-11 17:47:19.118 10855-10855/? E/zygote: No implementation found for void com.rj.maoshun.widget.scanbar.Qr.Symbol.init() (tried Java_com_rj_maoshun_widget_scanbar_Qr_Symbol_init and Java_com_rj_maoshun_widget_scanbar_Qr_Symbol_init__)
01-11 17:47:19.121 10855-10855/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rj.maoshun, PID: 10855
    java.lang.UnsatisfiedLinkError: No implementation found for void com.rj.maoshun.widget.scanbar.Qr.Symbol.init() (tried Java_com_rj_maoshun_widget_scanbar_Qr_Symbol_init and Java_com_rj_maoshun_widget_scanbar_Qr_Symbol_init__)
        at com.rj.maoshun.widget.scanbar.Qr.Symbol.init(Native Method)
        at com.rj.maoshun.widget.scanbar.Qr.Symbol.<clinit>(Symbol.java:163)
        at com.rj.maoshun.widget.scanbar.QRActivity.onCreate(QRActivity.java:58)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by bertsir** [comment]
修改包以后要修改so
