### ISSUE TITLE
在Eclipse中 运行到这里 Symbol.scanType = options.getScan_type(); 直接闪退

### ISSUE THREAD

**Issue by y2t25** [bertsir/zBarLibary#54]
在Eclipse中 运行到这里 Symbol.scanType = options.getScan_type(); 直接闪退

**Comment by bertsir** [comment]
@y2t25 日志什么

**Comment by y2t25** [comment]
Symbol.java 这个类

static {
        System.loadLibrary("zbar");
        init();
    }
init()这个方法报错

**Comment by y2t25** [comment]
错误信息如下：
java.lang.UnsatisfiedLinkError: No implementation found for void com.jaka.zbar.Qr.Symbol.init() (tried Java_com_jaka_zbar_Qr_Symbol_init and Java_com_jaka_zbar_Qr_Symbol_init__)
	at com.jaka.zbar.Qr.Symbol.init(Native Method)
	at com.jaka.zbar.Qr.Symbol.<clinit>(Symbol.java:168)
	at com.jaka.zbar.QRActivity.onCreate(QRActivity.java:89)
	at android.app.Activity.performCreate(Activity.java:7088)
	at android.app.Activity.performCreate(Activity.java:7079)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by bertsir** [comment]
@y2t25 改了包名要重新编译so  jni文件夹下zbarjni.c里的cn_bertsir_zbar换成你的包名  然后ndk-build

**Comment by y2t25** [comment]
好的，谢谢，我试下
