### ISSUE TITLE
作者源码魅族手机扫码闪退

### ISSUE THREAD

**Issue by BlissYang91** [bertsir/zBarLibary#59]
Process: cn.bertsir.qrtest, PID: 29393
    java.lang.IllegalArgumentException: Both dimensions must be greater than 0
        at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:50)
        at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:98)
        at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:86)
        at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
        at cn.bertsir.zbar.CameraScanAnalysis$2.run(CameraScanAnalysis.java:171)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by bertsir** [comment]
@BlissYang91  关闭自动拉近，魅族什么机型

**Comment by BlissYang91** [comment]
魅族V8，你可以试一下

**Comment by BlissYang91** [comment]
我就是想用自动拉进的功能，请问有没有修改方案？

**Comment by BlissYang91** [comment]
给你发了邮件
