### ISSUE TITLE
大神，这是

### ISSUE THREAD

**Issue by Yang4an** [bertsir/zBarLibary#63]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.autohome.heycar-R-UHk8a4K1pEQ6S8G5x-ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.autohome.heycar-R-UHk8a4K1pEQ6S8G5x-ig==/lib/arm, /data/app/com.autohome.heycar-R-UHk8a4K1pEQ6S8G5x-ig==/base.apk!/lib/armeabi, /system/lib]]] couldn't find "libzbar.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at cn.bertsir.zbar.Qr.Symbol.<clinit>(Symbol.java:167)
        at cn.bertsir.zbar.QRActivity.onCreate(QRActivity.java:92)
        at android.app.Activity.performCreate(Activity.java:7441)
        at android.app.Activity.performCreate(Activity.java:7431)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3343)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by bertsir** [comment]
@Yang4an 先检查文件是否齐全，在看so的平台匹配不
