### ISSUE TITLE
选相册图片识别后会报这个错

### ISSUE THREAD

**Issue by lucifinilsu** [bertsir/zBarLibary#83]
2019-09-18 14:45:51.997 17366-17366/? W/System.err: java.lang.RuntimeException: autoFocus failed
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.hardware.Camera.native_autoFocus(Native Method)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.hardware.Camera.autoFocus(Camera.java:1435)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at cn.bertsir.zbar.CameraManager.autoFocus(CameraManager.java:154)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at cn.bertsir.zbar.CameraPreview.startCameraPreview(CameraPreview.java:99)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at cn.bertsir.zbar.CameraPreview.start(CameraPreview.java:81)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at cn.bertsir.zbar.QRActivity.onResume(QRActivity.java:113)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.Activity.performResume(Activity.java:7614)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4412)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:112)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.os.Looper.loop(Looper.java:216)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2019-09-18 14:45:51.997 17366-17366/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by bertsir** [comment]
@lucifinilsu 有崩溃么

**Comment by lucifinilsu** [comment]
> @lucifinilsu 有崩溃么

倒是没有崩溃

**Comment by bertsir** [comment]
@lucifinilsu 这个在相机持续预览的时候会有对焦失败的可能性，算正常
