### ISSUE TITLE
对一些较大的本地图片会报错

### ISSUE THREAD

**Issue by lucifinilsu** [bertsir/zBarLibary#85]
2019-09-18 15:03:19.835 17366-22423/? W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=929; index=-506
2019-09-18 15:03:19.835 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.ec.ModulusGF.multiply(ModulusGF.java:105)
2019-09-18 15:03:19.835 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.ec.ModulusPoly.evaluateAt(ModulusPoly.java:99)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.ec.ErrorCorrection.decode(ErrorCorrection.java:53)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.correctErrors(PDF417ScanningDecoder.java:557)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:530)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:309)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:278)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:124)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
2019-09-18 15:03:19.836 17366-22423/? W/System.err:     at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at cn.bertsir.zbar.CameraScanAnalysis.decode(CameraScanAnalysis.java:279)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at cn.bertsir.zbar.CameraScanAnalysis.access$1200(CameraScanAnalysis.java:57)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at cn.bertsir.zbar.CameraScanAnalysis$2.run(CameraScanAnalysis.java:239)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-09-18 15:03:19.837 17366-22423/? W/System.err:     at java.lang.Thread.run(Thread.java:784)

**Comment by bertsir** [comment]
@lucifinilsu 多大的图片，这个还没遇到过

**Comment by lucifinilsu** [comment]
> @lucifinilsu 多大的图片，这个还没遇到过

手机拍的，10M

**Comment by bertsir** [comment]
@lucifinilsu 开启裁剪呢

**Comment by lucifinilsu** [comment]
> @lucifinilsu 开启裁剪呢

现在又没有了，不是每次都报

**Comment by bertsir** [comment]
@lucifinilsu 好的 我调整一下
