### ISSUE TITLE
1.3.7报错崩溃

### ISSUE THREAD

**Issue by lucifinilsu** [bertsir/zBarLibary#86]
2019-09-18 18:30:27.451 18993-18993/? W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/xxxx-XjcRDlH6WrU5ySdyjl62_w==/base.apk"],nativeLibraryDirectories=[/data/app/xxxx-XjcRDlH6WrU5ySdyjl62_w==/lib/arm, /data/app/xxxxxx-XjcRDlH6WrU5ySdyjl62_w==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libzbar.so"
2019-09-18 18:30:27.451 18993-18993/? W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
2019-09-18 18:30:27.451 18993-18993/? W/System.err:     at java.lang.System.loadLibrary(System.java:1672)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at cn.bertsir.zbar.Qr.Symbol.<clinit>(Symbol.java:185)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at cn.bertsir.zbar.QRActivity.onCreate(QRActivity.java:95)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7458)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7448)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2019-09-18 18:30:27.452 18993-18993/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:112)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at android.os.Looper.loop(Looper.java:216)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7625)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2019-09-18 18:30:27.453 18993-18993/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by bertsir** [comment]
@lucifinilsu 确实是打包的aar有问题，好诡异

**Comment by bertsir** [comment]
@lucifinilsu 方便留个联系方式么

**Comment by lucifinilsu** [comment]
> @lucifinilsu 方便留个联系方式么

QQ 1052294209 ，我重新build一遍又好了
