### ISSUE TITLE
从1.3.4更新1.3.9版本出错

### ISSUE THREAD

**Issue by lan2000** [bertsir/zBarLibary#88]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar",     =/base.apk!/lib/armeabi, /system/lib, /product/lib]]] couldn't find "libzbar.so" at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at cn.bertsir.zbar.Qr.Symbol.<clinit>(Symbol.java:185)
        at cn.bertsir.zbar.QRActivity.initParm(QRActivity.java:111)
        at cn.bertsir.zbar.QRActivity.onCreate(QRActivity.java:84)

项目当前abiFilters "armeabi"

**Comment by lan2000** [comment]
好吧是本地调试工具出现的问题，重新clean project就ok了。
