### ISSUE TITLE
扫描时会有20%的几率出现这个bug

### ISSUE THREAD

**Issue by striveprince** [bertsir/zBarLibary#98]
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at cn.bertsir.zbar.CameraScanAnalysis.decode(CameraScanAnalysis.java:288)
        at cn.bertsir.zbar.CameraScanAnalysis.access$1200(CameraScanAnalysis.java:57)
        at cn.bertsir.zbar.CameraScanAnalysis$2.run(CameraScanAnalysis.java:248)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by bertsir** [comment]
@striveprince 降低zxing版本试试

**Comment by striveprince** [comment]
那降低到什么版本好呢

**Comment by striveprince** [comment]
我把版本降低到3.3.0，然后发现正常扫描时没有问题的，但是如果二维码侧着扫描会有这个问题

**Comment by frinda** [comment]
这个问题没有好的解决办法？

**Comment by Tang0504** [comment]
我也遇到了这个问题  还挺多人出现的  但是我刻意去测试无法复现，，，不知道用户是怎么复现的，麻烦有解决办法了回复一下我
